### ISSUE TITLE
Create Jenkins pipeline

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/smartling-cli#10]
We use jenkins as CI. We need a build plan which will build and upload files on S3.

**DoD**
* Create jenkins pipeline  (declarative pipeline)
  * Build binaries for 3 platforms: linux, mac, win
  * Upload binaries to s3
  * Send message to slack channel in case of error
* Assume that jenkins doesn't have installed go, but has docker and aws cli. So build should happen in docker container
* Pipeline input parameters:
  * Target s3 bucket and folder. Default value `s3://smartling-connectors-releases/cli`
  * Slack channel name

**Comment by dimitrystd** [comment]
@seletskiy Can you add a Makefile which will build for linux, darwin, windows (all amd64)?

**Comment by seletskiy** [comment]
https://github.com/Smartling/smartling-cli/blob/v2/Makefile

**Comment by dimitrystd** [comment]
@seletskiy I modified makefile but it returns error now
```
$ make
rm -rf ./bin
mkdir ./bin
go get
GOOS=darwin go build -o bin/smartling.darwin
GOOS=windows go build -o bin/smartling.windows.exe
GOOS=linux go build -o bin/smartling.linux
GOOS=all go build -o bin/smartling.all
cmd/go: unsupported GOOS/GOARCH pair all/amd64
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 2
```
I added workaround in 9207c32dbe97e859455fa2f3856e6d4a52811ac0, but would like to get it rid. Can you fix makefile, i don't understand where is issue.

**Comment by seletskiy** [comment]
@dimitrystd: done
