### ISSUE TITLE
Add more details about error in verbose mode

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/smartling-cli#12]
**Steps**:
I forgot to configure account id or specified wrong one.
```
>cli.exe -p 2f23eaae9 projects list -a 2f23e -v
ERROR: unable to list projects
└─ failed to get projects list: unable to decode JSON response: EOF
```
Would be nice to get more details in verbose mode. Let's write response output if we cannot parse it.

**Comment by dimitrystd** [comment]
One more case where would be nice to see what exactly was responded
```
>cli -v files list
unable to list files in project "2f2xxxxxx"
└─ failed to get files list: unable to authenticate: authenticate request failed: API call returned non-200 status code: 404
```

**Comment by seletskiy** [comment]
@dimitrystd: I've done with better error reporting (in case of unidentified API error there will be full report with reply headers and reply body). With verbose mode one (`-vv`) log will include API replies and X-SL-Requestid header as well.
