### ISSUE TITLE
Add command to get list of locales

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/smartling-cli#13]
Returns list of target locales
```
$ cli projects <project id> locales
de-DE German (Germany) true
es-ES Spanish          false
```
* `<project id>`: optional. Should be taken from configuration
* --format=[]: Pretty-print containers using a Go template. Default value "{{.localeId}}\t{{.description}}\t{{.enabled}}"
* -s|--source: Return source locale instead of target locales
* -q|--quiet: Only display locale code

**Comment by seletskiy** [comment]
Done.
