### ISSUE TITLE
Don't apply pull format for source files

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/smartling-cli#16]
```
>cli.exe files status test_translation_progress.properties
test_translation_progress@.properties       en-US  missing  source  5  20
test_translation_progress@be-BY.properties  be-BY  missing  0%      0  0
test_translation_progress@de-DE.properties  de-DE  missing  0%      0  0
```
You may notice that source file contains `@`. We should use  `pull format` from configuration only for translated files.

**Comment by seletskiy** [comment]
@dimitrystd: Please, paste format value from configuration file. It should probably contain `if`, as in default format.

**Comment by seletskiy** [comment]
@dimitrystd: It maybe useful to apply format so I prefer to keep it, just include condition in it so extra `@` will not be added. See updated example config file for more info.
