### ISSUE TITLE
No error message in case of querying non-existing file

### ISSUE THREAD

**Issue by msogin** [Smartling/smartling-cli#24]
smartling-cli files status asdfasdf
smartling-cli files pull asdfasdf

both commands return empty output. There should be an API error message instead.
there should also be non-zero status code return in this case

smartling-cli files pull asdfasdf; echo $?
0

**Comment by dimitrystd** [comment]
If cli is not configured then i see
```
ERROR: user ID is not specified.

Either specify --user command line option or set "user_id" option in the configuration file:

smartling.yml:
        user_id: "PUT_VALUE_HERE"
```
which is expected.
So i assume you configured cli before. The empty output is expected because `asdfasdf` is treated as fileUri.

Is it common case for linux to return non-zero in case of no error but empty result?

**Comment by dimitrystd** [comment]
So after discussing the desired behaviour we have following requirements:
* Let's have the same behavior like standard `ls` command
  * Write error message to `stderr`. Message can be `smartling-cli: asdfasdf: No such file`
  * Return status code 1
* Update following commands
  * `status`
  * `push`
  * `pull`
  * `list`

**Comment by dimitrystd** [comment]
Do i understand correct that change was done only for `list` command?

**Comment by seletskiy** [comment]
@dimitrystd: No, it was done for all commands that are support globbing.
