### ISSUE TITLE
Add progress for files status command

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/smartling-cli#26]
I have seen how people uses `files status` command. The  problem with waiting time, it can take 10-30 sec on average project, but people doesn't see any feedback from cli after 5-10sec and terminate the command.

Possible solutions:
* (optional) Render information per file right after receiving it. Right now table is rendered when is completed
* (required) Show progress to user. Something like `Progress 10%`

**DoD**:
Write live progress to `stderr`

**Comment by seletskiy** [comment]
@dimitrystd: I've added very simple progress indicator to files status command, both for *nix and windows.

**Comment by seletskiy** [comment]
@dimitrystd: It's impossible to render evenly spaced table (e.g. properly columnized) and render data as soon as it comes from API. So, we need to choose: a) render table properly when data is ready; b) or render not columnzied properly but when next chunk of data arrives.

**Comment by dimitrystd** [comment]
Is it possible to write a progress into `stderr` and then render table when data is ready?

**Comment by seletskiy** [comment]
@dimitrystd: It's already done.

**Comment by dimitrystd** [comment]
Tested
