### ISSUE TITLE
Import translations

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/smartling-cli#29]
Import an existing translations is popular use case in CS team. Import operation means you have:
* The original file
* One or more files with translations
* You do regular upload or the original file
* Then upload file with translations. You should specify for which locale you have translations

In the original requirements the import was part of `files push` command. But i think we should not to add a complexity here. So let's add the new command `files import`.
Documentation: https://help.smartling.com/v1.0/reference#post_projects-projectid-locales-localeid-file-import

**DoD**:
* The new command
```
smartling-cli import <original uri> -t <path to file with translations> -l <locale> [--type <type>] [--state <translationState>] [--overwrite=true|false]
```
* Parameters:
  * `<original uri>` - mandatory
  * `-t` - mandatory
  * `-l|--locale` - mandatory
  * `--type` - optional. Automatically detect by extension
  * `--state` - optional. Default `POST_TRANSLATION`
  * `--overwrite` - optional. Default `true`

**Comment by seletskiy** [comment]
@dimitrystd: Can you test it? I have trouble testing it.

**Comment by dimitrystd** [comment]
Created 2 files
* [test-import.properties.txt](https://github.com/Smartling/smartling-cli/files/1122163/test-import.properties.txt)
* [test-import-es.properties.txt](https://github.com/Smartling/smartling-cli/files/1122164/test-import-es.properties.txt)

Manually uploaded the original file into the dashboard, then imported the 2nd file. See translations, everything is fine.

Tried to repeat steps by cli
```
>dir
04-07-17  04:11 PM                36 test-import-es.properties
04-07-17  04:10 PM                35 test-import.properties

>cli files import test-import.properties test-import-es.properties es --published
Usage:
  smartling [options] [-v]... init --help
  smartling [options] [-v]... init [--dry-run]
```
So looks like it expects some additional params.

Also, as far as i understand, the `state` is the mandatory parameter. Can we make it optional? We should remember that users are lazy
```
  smartling [options] [-v]... import <uri> <file> <locale> (--published|--post-translation)
                                           [--type=] [--overwrite]
```

**Comment by seletskiy** [comment]
@dimitrystd: It's `smartling import`, not `smartling files import` (as in yours issue description of DoD).

**Comment by seletskiy** [comment]
@dimitrystd: state is mandatory just because it's mandatory in API. What value should CLI assume if no is explicitly given?

**Comment by dimitrystd** [comment]
But import is applicable only for files for now. And it's defined in File API. So i think it will be more straight forward to use `files import`

Use `POST_TRANSLATION`
>`--state` - optional. Default `POST_TRANSLATION`

**Comment by seletskiy** [comment]
@dimitrystd: fixed and tested.
