### ISSUE TITLE
Support credentials from env vatiables

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/smartling-cli#31]
The use case:
The CLI tool is used as part of bash script. The script is called inside docker or by CI server. It will be convenient:
* Don't specify credentials in script (command line parameters)
* In config file (because it can be committed into repository)

So we can use env variables like
```
smartling-cli --project $PROJECT --user $USER --secret $PASS
```
But ideal case will be if CLI will check env variables automatically.

**DoD**
* The CLI looks for credentials and configuration settings in the following order:
  * Command Line Options
  * Environment Variables
  * The configuration file

**Comment by seletskiy** [comment]
@dimitrystd: Done.
