### ISSUE TITLE
token secret is written to yaml file in plaintext

### ISSUE THREAD

**Issue by enegron-sl** [Smartling/smartling-cli#33]
isn't this a security concern?

**Comment by dimitrystd** [comment]
Well, i did some research but didn't find how we can encrypt data when everything on clients side (data; application). I mean we can add some encryption but it will require some input from user. So don't see any sense in this.
User has following options:
- put config into his home dir
- don't put credentials into config and pass them in the command line for each request
- use env variables

Let me know if you have better ideas.
