### ISSUE TITLE
User ID isn't unescaped when authorizing

### ISSUE THREAD

**Issue by dkBrazz** [Smartling/smartling-cli#35]
When User Id is entered it might be escaped before saving into config, but when authenticating it isn't unescaped.
There are also redundant method of escaping is used for User Id - symbol `+` doesn't require escaping for YAML strings

```
$> smartling-cli.exe init
Generating smartling.yml...
Enter User ID: test+marketo@smartling.com
Enter Token Secret: secret
Enter Account ID (optional):
Enter Project ID:
```

smartling.yml:
```
user_id:
    "test&#43;marketo@smartling.com"

secret:
    "secret"
```
With escaped `+` authentication fails, but when I manually replace `&#43;` with `+` in config it works

If you do several re-inits (with existing config) leaving default values, you get this result in config:
```
user_id:
    "test&amp;amp;#43;marketo@smartling.com"
```
`&` symbol is also escaped, and then escaped again and again

**Comment by seletskiy** [comment]
@dimitrystd: To fix it replace `html/template` to `text/template` on https://github.com/Smartling/smartling-cli/blob/master/config_template.go#L4

**Comment by dimitrystd** [comment]
Verified
