### ISSUE TITLE
Test connection during init command

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/smartling-cli#37]
Would be nice to test a connection when user uses `init` command.

**DoD**:
Try to get project info when user completed configuration. Make this process clear for user. 
* Print in console right after saving configuration
```
Test connection to Smartling API. Receive information about the project...
Test connection is successful
```
Or if `response != SUCCESS`
```
Test connection to Smartling API. Receive information about the project...
Test connection is failed.
<Additional error info here>
```
* If we got 401 from authentication API then print `Your credentials are invalid`
* For any other errors print error message from JSON response

**Comment by seletskiy** [comment]
@dimitrystd: Check it out.

**Comment by dimitrystd** [comment]
Confirm
