### ISSUE TITLE
Consider where to store configuration file (home dir vs work dir)

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/smartling-cli#38]
_Received from user feedback_

The original design was built around the use case with localization manager. You as localization manager have multiple projects, each one in a separate folder. Each project may have different settings. Smartling credentials are just part of settings. Also, settings may contain file patterns and upload\download configuration. So it's convenient to keep CLI configuration right in a project folder.

One of the feedbacks contained following steps:
* Install CLI
* Run `init` command
* Switch to folder with test files or create such folder
* Run `files push` command

User got the error that `user identifier` is not configured. He added user into command line, then he got the error about `user secret` and so on. So he didn't realize that `smartling.yml` was created in his home dir, but CLI looks for it in work dir.

**DoD**:
CLI must work from project root and **subfolders**. People expect behavior like in git. You can run `git pull` from root folder (where `.git` exists) or from any subfolder.
It means that CLI must look for config file in the current folder or parent folders
* We continue to use the same order for looking context as described in #31. But we extend the last item - where to search for `smartling.yml`
* If we didn't find the mandatory configuration in Env variables or command line, and we cannot find config in the current or parent folders then write error:
  ```
  ERROR: Cannot find the mandatory configuration "user_id"

  The current or any of the parent directories don't contain "smartling.yml"
  Please either specify:
  - Environment variable "SMARTLING_USER_ID"
  - Command line option "--user"
  - Or set "user_id" option in the configuration file:
  smartling.yml:
	user_id: "PUT_VALUE_HERE"
  ```

**Comment by dimitrystd** [comment]
Updated description after an internal conversation. We continue to use the same approach but make error more user friendly

**Comment by seletskiy** [comment]
@dimitrystd: Check it out. Also, `-vv` flag can be used to look where CLI is looking for config file and which one is used.

**Comment by dimitrystd** [comment]
Reopened. Added comments in commit but don't see them now.
I cannot pass basic flow
```
$ smartling-cli init
ERROR: no configuration file "smartling.yml" found

Ensure, that config file exists either in the current directory or in any parent directory.
```

**Comment by seletskiy** [comment]
@dimitrystd: Check it out.

**Comment by dimitrystd** [comment]
Verified
