### ISSUE TITLE
Allow to push files with relative path

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/smartling-cli#39]
_Issue came from feedback_

User tried to push files
```
smartling-cli files push ./test.txt
smartling-cli files push ~/Projects/Smartling/example files/test.txt
```
But got error that file not found.
But if you try to submit the same files as
```
smartling-cli files push test.txt
smartling-cli files push Smartling/example\ files/test.txt
 ```
then it works.

CLI should work as git. You can use absolute and relative paths in git commands.

**DoD**:
Change flow how we work with files:
* Let's say `config_root` is folder where we store `smartling.yml`
* Resolve all paths to absolute path
* Validate that absolute file path is subpath of `config_root`
  * If no then ignore file and write error
* Calculate relative file path relatively `config_root`. An example
```
user provided path=~/Projects/Smartling/example\ files/test.txt
config_root=/Users/xxx/Projects/Smartling
absolute path=/Users/xxx/Projects/Smartling/example\ files/test.txt
relative path=example\ files/test.txt
```
* Use absolute path for reading file content. Use relative path as `FileUri`

**Comment by dimitrystd** [comment]
Still not sure about action points for this task. I think we should accept any path (absolute\relative), but:
* make sure that file is inside work dir. An example, `work dir = ~/Projects/Smartling`, then the following command should fail
    ```
    smartling-cli files push ~/Temp/test.txt
    ```
* build `fileUri` starting from work dir. An example, `work dir = ~/Projects/Smartling` then if i push
    ```
    smartling-cli files push ~/Projects/Smartling/example files/test.txt
    ```
    then `fileUri=example files/test.txt`

@enegron-sl what do you think?

**Comment by dimitrystd** [comment]
Updated ticket description after internal conversation

**Comment by seletskiy** [comment]
@dimitrystd: It was complex change, can you test it?

Implementation limitations are that following patterns will not work:

* `../*/../file.txt` (however, `../file.txt` and `../*/file.txt` **will** work);
* `dir/{,other/}file.txt`;

**Comment by dimitrystd** [comment]
Thanks for mention patterns, I completely forgot about them. Patterns support is definitely required, but i don't expect something complex than `src/**/*.xml`. Do we have some formal description what will not work? So i'm ok to add to documentation limitations to use patterns in relative paths.

So far i tried to test with simple relative paths. In examples below CLI calculates from `file URI`. My test workspace structure:
```
/tmp/cli/smartling.yml
/tmp/cli/dir1/dir11/test.cml
```
where `config_root=/tmp/cli`.

```
$ cd /tmp/cli/dir1/dir11
$ smartling-cli files push test.xml
test.xml (xml) new [1 strings 27 words]
```
Expected file uri `dir1/dir11/test.cml`. In requirements
>Calculate relative file path relatively `config_root`. An example

The 2nd similar test
```
$ cd /tmp/cli/dir1
$ smartling-cli files push dir11/test.xml
dir11/test.xml (xml) overwritten [1 strings 27 words]
```
I again expected `dir1/dir11/test.cml`.
The idea to make it similar to git. Doesn't matter from wich folder you will call `git commit`, new files fill be committed with proper path.

**Comment by seletskiy** [comment]
> Thanks for mention patterns, I completely forgot about them. Patterns support is definitely required, but i don't expect something complex than src/**/*.xml. Do we have some formal description what will not work? So i'm ok to add to documentation limitations to use patterns in relative paths.

Basically, any pattern, which contains `..` after `*` or `**` will not work.

Implementation is very simple right now: a) take non-pattern (e.g. without `*`, `{}`, eth) prefix from path till last available `/` and use it as lookup directory; b) check if there's file named exactly as specified path; c) otherwise, run recursive search in directory, obtained at step (a).

**Comment by seletskiy** [comment]
@dimitrystd: Also, please check out behavior again, I guess it's fixed now.

**Comment by dimitrystd** [comment]
Verified
