### ISSUE TITLE
What is benefit of using "manul" instead of "dep" now?

### ISSUE THREAD

**Issue by mdreizin** [Smartling/smartling-cli#42]
It is not a holy-war question, but I would like to know that :)

For now `dep` solves a lot of issues that `manul` tried to solve.

Using `dep` gives a lot of advantages comparing with [set of similar tools](https://github.com/golang/go/wiki/PackageManagementTools).

Do you mind if I replace `manul` with `get`?

**Comment by seletskiy** [comment]
@mdreizin: https://github.com/kovetskiy/manul#whats-the-reason-for-yet-another-utility

The main advantage is that project repo will not contain `vendor/` directory, which essentially will lead to big repo and slow go get/git clone. manul also does not have any `lock` or `spec` files, it operates purely on `.gitmodules`.

**Comment by mdreizin** [comment]
@seletskiy I have already read that section ;)

I just asking, because I'm preparing a couple of fixes and `manul` does not have convenient way to switch between versions of deps.

**Comment by mdreizin** [comment]
@seletskiy Feel free to close it if you don't want to switch to `dep` (official dependency management tool).

I hope it will support submodules soon ;)

**Comment by seletskiy** [comment]
@mdreizin: If you have problems with manul, you can switch.

**Comment by seletskiy** [comment]
@mdreizin: BTW what problems do you have with switching between versions?
