### ISSUE TITLE
question: benefit of 99designs/smartling fork

### ISSUE THREAD

**Issue by mdreizin** [Smartling/smartling-cli#45]
What is benefit to use `99designs/smartling` fork rather than bare repo?

Currently this repo doesn't have nothing in common with `99designs/smartling`.

Are you planning to merge them?

**Comment by dimitrystd** [comment]
The initial plan was to adopt existing code and add just cosmetics changes. But in the middle of refactoring we started to do major changes. So far no plans to merge our code back.
Would you like to suggest to adopt your version of CLI? :)

**Comment by mdreizin** [comment]
@dimitrystd Thanks for the answer.

I will try my best to help you and also merge best features of both tools.

**Comment by mdreizin** [comment]
@dimitrystd I would prefer to keep only one solution and I hope it will be this one (`Smartling/smartling-cli`).
