### ISSUE TITLE
Add support for HTTPs proxy

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/smartling-cli#5]
It's common case when you have access to internet only via corporate web proxy. In some cases proxy configuration can be get from env variables. But we develop tool which should work on any OS, so better to do explicit configuration (we had such experience with other our connectors).

**DoD**:
* Add to config file the new configuration `https.proxy`
* It has following format `https.proxy https://username%40company.com:password@proxyserverIP:port`. (i took it from git, so feel free to split on `https.proxy`, `https.proxy-user` if required)
* Add description text: `[protocol://][user[:password]@]host[:port] Use proxy on given port`

**Comment by seletskiy** [comment]
@dimitrystd: done.

**Comment by dimitrystd** [comment]
tested
