### ISSUE TITLE
feat: project alias

### ISSUE THREAD

**Issue by mdreizin** [Smartling/smartling-cli#50]
It would be nice to have ability to add prefix/alias to uploaded files. Please see https://github.com/Fitbit/smartling#usage

If you are going to upload file with `foo/bar.json` and you set `alias` to `baz` then the full `fileURI` would be `baz/foo/bar.json`.

It would be very useful if you have one project to upload files/translations from different places.

**Comment by dimitrystd** [comment]
We have `--branch=` option for this. It may detect the actual name of git branch or you can set name manually.

**Comment by mdreizin** [comment]
@dimitrystd Thandk for letting me know. I will try this option.
