### ISSUE TITLE
how is namespace supported in files push?

### ISSUE THREAD

**Issue by shiqi** [Smartling/smartling-cli#51]
I am trying to migrate my scripts from smartling-api shell to the smartling-cli (based on the recommendation from the readme in the smartling-api repo), just wonder how am I supposed to assign the value of smartling.namespace for file uploads (files push in corresponding to the smartling-cli calls) 

the only part as I search either docs or the source code of smartling-cli, is in the yaml config file as part of the directives, however, according to the doc here
https://help.smartling.com/v1.0/reference#upload (btw this is a very confusing url since it says 1.0 but the content of the page says it is actually 2.0) 

"while this parameter shares the format of other file directives, it will not work as an inline directive and must be specified in the API call."

if the above statement doesn't apply here, how do I specify in the yaml config file that when I call things like

>smartling-cli files push *.txt -branch test-branch

in hope to upload several .txt files with one call,  and have each of them have the namespace set to its filename instead of its uri? 

(for example, if I have a menu.txt I want to upload it with uri `test-branch/menu.txt` but I want the namespace to remain to be `menu.txt`, is that by default or how do I set up my yaml file to achieve that?)

**Comment by dimitrystd** [comment]
Look at example [there](https://github.com/Smartling/smartling-cli/issues/34#issuecomment-335313221)
