### ISSUE TITLE
Allow to ignore SSL error

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/smartling-cli#6]
Another popular case when corporate proxy sniffs ssl traffic and local certification authority is not configured right. As result localization manager is blocked and complains to smartling that its connector doesn't work.

**DoD**:
Add the new global option to CLI 
```
-k, --insecure      Allow connections to SSL sites without certs
```

**Comment by seletskiy** [comment]
@dimitrystd: done.

**Comment by dimitrystd** [comment]
Tested
