### ISSUE TITLE
Ability to have CLI ignore errors

### ISSUE THREAD

**Issue by russell-banton** [Smartling/smartling-cli#63]
When I am uploading a directory that contains a lot of folders I run into issues with Smartling erroring on some files which stops the process. I would like the CLI to continuing running and then provide a report of any files that were not successful in pushing to Smartling.

**Comment by dimitrystd** [comment]
**DoD**:
If an error happens then:
* Continue to upload files
* Write error to `stderr` 
* Return code=1 (let's review what already we return for other commands)
