### ISSUE TITLE
Cannot find config in windows

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/smartling-cli#7]
**Steps**:
* Create config folder in work dir `mkdir -p .config\smartling`  (important, it's windows)
* Put valid `config.yml` there
![d__projects_connectors_smartling-cli_ config_smartling-001036](https://user-images.githubusercontent.com/1511122/27145077-f4c80170-513c-11e7-8f35-83ce54c001a1.png)
* Run app
```
smartling-cli>smartling-cli.exe -p 8999a0e9c projects info 8999a0e9c
ERROR: user ID is not specified.

Either specify --user command line option or set "user_id" option in the configuration file:

/.config/smartling/config.yml:
        user_id: "PUT_VALUE_HERE"
```

**Actual**:
`user_id` is defined in config but cannot be found

**Comment by dimitrystd** [comment]
I'm not sure that home folder is a good place for config. It's like a `.git` folder, should be together with resource files.

**Comment by seletskiy** [comment]
Fixed.
