### ISSUE TITLE
Add detailed help for each command

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/smartling-cli#9]
Currently we have the help command which prints information about all commands. But in most cases user looks some details about particular command. And we plan to update extend documentation, so some options my have a long description.

**DoD**:
* Show just a common information about CLI by `-h | --help`
```
$ cli -h
// TBD example
```
* Show detailed information for each command
```
$ cli files list -h
// TBD example
```

**Comment by seletskiy** [comment]
It's done for currently implemented commands.
